### ISSUE TITLE
Cannot run the UML Platform examples

### ISSUE THREAD

**Issue by smishy05** [xatkit-bot-platform/xatkit#28]
Hi there,

I wish to run the UML platform using Xatkit. It was not present in the `platforms` directory after the initial `build`. Therefore, this is what I did:

1) In the `platforms` directory, I cloned the `xatkit-uml-platform`.

2) Then, I went into the `build/bin` directory and then, ran this command - `./start-xatkit-linux.sh ../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties`. After doing this, I get this error - 

```
Xatkit classpath:
/home/shailesh1998/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-github-platform/xatkit-github-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-chat-platform/xatkit-chat-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-slack-platform/xatkit-slack-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-log-platform/xatkit-log-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-core-platform/xatkit-core-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-react-platform/xatkit-react-runtime-4.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-rest-platform/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/bin/xatkit-nodep-jar-with-dependencies.jar
java -Dfile.encoding=UTF-8 -cp '/home/shailesh1998/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-github-platform/xatkit-github-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-chat-platform/xatkit-chat-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-slack-platform/xatkit-slack-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-log-platform/xatkit-log-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-core-platform/xatkit-core-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-react-platform/xatkit-react-runtime-4.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-rest-platform/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/bin/xatkit-nodep-jar-with-dependencies.jar' com.xatkit.Xatkit '../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties'
22:18:14.093 [pool-3-thread-1] INFO   - Starting Xatkit with the configuration file ../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties
22:18:15.604 [pool-3-thread-1] INFO   - Loading Xatkit core libraries
22:18:15.706 [pool-3-thread-1] INFO   - 	CoreLibrary loaded
22:18:15.706 [pool-3-thread-1] INFO   - Loading Xatkit core platforms
22:18:15.941 [pool-3-thread-1] INFO   - 	GithubPlatform loaded
22:18:15.943 [pool-3-thread-1] INFO   - 	ChatPlatform loaded
22:18:15.951 [pool-3-thread-1] INFO   - 	SlackPlatform loaded
22:18:15.953 [pool-3-thread-1] INFO   - 	LogPlatform loaded
22:18:15.956 [pool-3-thread-1] INFO   - 	CorePlatform loaded
22:18:15.959 [pool-3-thread-1] INFO   - 	ReactPlatform loaded
22:18:15.966 [pool-3-thread-1] INFO   - 	RestPlatform loaded
22:18:15.967 [pool-3-thread-1] INFO   - Loading Xatkit custom libraries
22:18:15.976 [pool-3-thread-1] INFO   - 	null loaded
22:18:15.977 [pool-3-thread-1] INFO   - Loading Xatkit custom platforms
22:18:16.012 [pool-3-thread-1] ERROR  - An error occurred when starting the XatkitCore, trying to close started services
22:18:16.012 [pool-3-thread-1] ERROR  - Cannot start Xatkit, see the attached exception
com.xatkit.core.XatkitException: Cannot load the ExecutionModel at the given location: file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:187) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.core.XatkitCore.<init>(XatkitCore.java:159) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.Xatkit.main(Xatkit.java:93) ~[xatkit-nodep-jar-with-dependencies.jar:?]
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'executionRules' not found. (file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi, 4, 19)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:185) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	... 2 more
Caused by: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'executionRules' not found. (file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi, 4, 19)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.reportUnknownFeature(XMLHandler.java:2045) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleUnknownFeature(XMLHandler.java:2009) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.handleUnknownFeature(XMIHandler.java:172) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleFeature(XMLHandler.java:1953) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1048) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:82) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1359) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327) ~[?:1.8.0_252]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:185) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	... 2 more
```

I am not too sure if I proceeded in the right way. Please kindly help.

Eager to hear from you!

Thanks in advance.

**Comment by gdaniel** [comment]
Hi,

As you notices the UML platform is not part of the `platforms` directory. We made this platform some time ago as an experiment, and we don't have the resources to maintain it. The error you report seems to be related to the version of the Xatkit language: the `executionRules` feature indicates that you are loading an execution model defined with the previous rule-based language, and Xatkit core doesn't work with this language anymore.

Note that it's not only an issue with the example bot, the platform itself probably has some dependencies to a previous version of Xatkit that is not supported anymore.
