### ISSUE TITLE
Error running the WeatherBot with NLP.js

### ISSUE THREAD

**Issue by JPery** [xatkit-bot-platform/xatkit#34]
Hi,

I tried running the WeatherBot using the NLP.js engine. For that I used the following configuration:

``` lang-java
botConfiguration.addProperty("xatkit.nlpjs.agentId", "default");
botConfiguration.addProperty("xatkit.nlpjs.language", "en"); // Also tried en-US
botConfiguration.addProperty("xatkit.nlpjs.server", "http://localhost:8080");
```
With this configuration, the following error appears:

```
11:20:29.016 [pool-3-thread-1] INFO   - Using MapDB to store monitoring data
11:20:29.034 [pool-3-thread-1] INFO   - Starting intent recognition monitoring
11:20:29.215 [pool-3-thread-1] INFO   - Registered REST handler  at URI /analytics/monitoring (method=GET)
11:20:29.216 [pool-3-thread-1] INFO   - Registered REST handler  at URI /analytics/monitoring/session (method=GET)
11:20:29.216 [pool-3-thread-1] INFO   - Registered REST handler  at URI /analytics/monitoring/unmatched (method=GET)
11:20:29.216 [pool-3-thread-1] INFO   - Registered REST handler  at URI /analytics/monitoring/matched (method=GET)
11:20:29.216 [pool-3-thread-1] INFO   - Registered REST handler  at URI /analytics/monitoring/sessions/stats (method=GET)
11:20:29.219 [pool-3-thread-1] INFO   - Starting NLP.js Client
11:20:29.435 [main] INFO  com.corundumstudio.socketio.SocketIOServer - Session store / pubsub factory used: MemoryStoreFactory (local session store only)
11:20:29.580 [pool-3-thread-1] INFO   - Registered REST handler  at URI /admin (method=GET)
11:20:29.580 [pool-3-thread-1] INFO   - Registered REST handler  at URI /admin/css/xatkit.css (method=GET)
11:20:29.580 [pool-3-thread-1] INFO   - Registered REST handler  at URI /admin/js/xatkit.js (method=GET)
11:20:29.582 [nioEventLoopGroup-2-1] INFO  com.corundumstudio.socketio.SocketIOServer - SocketIO server started at port: 5001
11:20:29.589 [pool-3-thread-1] INFO   - Starting ReactEventProvider
11:20:29.591 [pool-3-thread-1] INFO   - Starting ReactIntentProvider
11:20:29.592 [pool-3-thread-1] INFO   - Registering execution rule events
11:20:29.697 [pool-3-thread-1] WARN   - Cannot find a mapping for the abstract entity city, returning the fallback entity (none)
11:20:29.697 [pool-3-thread-1] WARN   - Cannot find a mapping for the abstract entity city, returning the fallback entity (none)
11:20:29.699 [pool-3-thread-1] INFO   - Starting NLP.js agent training (this may take a few minutes)
11:20:31.766 [pool-3-thread-1] INFO   - NLP.js agent trained.
11:20:31.766 [pool-3-thread-1] INFO   - Starting XatkitServer
11:20:31.767 [pool-3-thread-1] INFO   - Registered REST handler  at URI /status (method=GET)
11:20:31.768 [pool-3-thread-1] INFO   - XatkitServer started, listening on port 5.000
11:20:31.768 [pool-3-thread-1] INFO   - Xatkit bot started
11:20:56.157 [pool-3-thread-1] INFO   - Detected Intent HowIsTheWeather (confidence 0,981) from query text "How is the weather today in Barcelona?" (com.xatkit.execution.impl.StateContextImpl@3da6be75 (configuration: {}, session: {}, contextId: 833917e4-e864-484c-92e5-14c5784346ae, origin: http://localhost:5000))
11:20:56.163 [pool-3-thread-1] ERROR  - An error occurred when executing the action GetJsonRequest
11:20:56.163 [pool-3-thread-1] ERROR  - java.lang.NullPointerException
	at com.mashape.unirest.request.HttpRequest.queryString(HttpRequest.java:127)
	at com.xatkit.plugins.rest.platform.action.GetJsonRequest.buildRequest(GetJsonRequest.java:43)
	at com.xatkit.plugins.rest.platform.action.RestRequest.compute(RestRequest.java:163)
	at com.xatkit.plugins.rest.platform.action.RestRequest.compute(RestRequest.java:31)
	at com.xatkit.core.platform.action.RuntimeAction.call(RuntimeAction.java:81)
	at com.xatkit.plugins.rest.platform.RestPlatform.getJsonRequest(RestPlatform.java:123)
	at com.xatkit.example.WeatherBot.lambda$main$0(WeatherBot.java:62)
	at com.xatkit.core.ExecutionService.executeBody(ExecutionService.java:105)
	at com.xatkit.core.ExecutionService.lambda$handleEventInstance$0(ExecutionService.java:249)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

11:20:56.164 [pool-3-thread-1] INFO   - Action GetJsonRequest executed in 2 ms
11:20:56.164 [pool-3-thread-1] ERROR  - An error occurred when executing the body of state PrintWeather
java.lang.NullPointerException: null
	at com.xatkit.example.WeatherBot.lambda$main$0(WeatherBot.java:65) ~[classes/:?]
	at com.xatkit.core.ExecutionService.executeBody(ExecutionService.java:105) ~[core-5.0.0-SNAPSHOT.jar:?]
	at com.xatkit.core.ExecutionService.lambda$handleEventInstance$0(ExecutionService.java:249) ~[core-5.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
11:20:56.168 [pool-3-thread-1] ERROR  - An error occurred when running the actions associated to the event HowIsTheWeather. Check the logs for additional information
11:20:56.168 [pool-3-thread-1] ERROR  - java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.xatkit.example.WeatherBot.lambda$main$0(WeatherBot.java:65)
	at com.xatkit.core.ExecutionService.executeBody(ExecutionService.java:105)
	at com.xatkit.core.ExecutionService.lambda$handleEventInstance$0(ExecutionService.java:249)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	... 3 more
```

It seems like the NLP.js engine has no mapping for the "city" entity, so it recognizes the intent but does not return the CITY parameter "cityName".

How can we fix that? Do we have to implement a custom mapping for the "city" entity?

Thanks!

**Comment by gdaniel** [comment]
Hi @JPery,

Indeed, NLP.js doesn't have a mapping for `city`, but this shouldn't be an issue here, if the built-in mapping doesn't exist we default to a more permissive one (similar to DialogFlow's `any` entity).

From your stack trace I guess the parameter value passed to the Rest platform is null, this suggests an (different) issue with the intent matching. Can you try the following input and let me know if it works better?

`How is the weather in Barcelona ?` (note the space before the question mark).

Note that our NLP.js integration needs some polishing, I am currently integrating a few features that should improve the overall matching quality.

**Comment by JPery** [comment]
Hi, @gdaniel! Thanks for your fast reply.

I think that, for some reason, NLP.js is not defaulting to the permisive mapping, as the log says `returning the fallback entity (none)`. Could be the problem that this mapping (none) returns always null?

Also, I tried the input `How is the weather in Barcelona ?` and it neither worked for me. It throws the same error as the previous log.

**Comment by gdaniel** [comment]
Ok, I'll reproduce it and get back to you with more information. 
In the meantime you can go for a custom mapping with a few city names. Once I will have fixed the issue you can then move back to the `city` entity.
